# Generated by Django 4.1.7 on 2023-03-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('country', models.CharField(blank=True, db_column='country', max_length=256, null=True)),
            ],
            options={
                'db_table': 'manufacturers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('last_scan', models.BigIntegerField(db_column='last_scan', max_length=256)),
            ],
            options={
                'db_table': 'retailers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('category_id', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.category')),
            ],
            options={
                'db_table': 'sub_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('catalog_number', models.BigIntegerField(db_column='catalog_number', max_length=256)),
                ('units', models.CharField(choices=[('ml', 'Milligram'), ('units', 'Unit'), ('g', 'Gram'), ('kg', 'Kilogram'), ('l', 'Liter')], db_column='units', max_length=128)),
                ('quantity', models.IntegerField(db_column='quantity', max_length=128)),
                ('discount_status', models.BooleanField(db_column='discount_status', default=False)),
                ('product_status', models.BooleanField(db_column='product_status', default=True)),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure', max_length=256)),
                ('unit_of_measure_price', models.IntegerField(db_column='unit_of_measure_price', max_length=128)),
                ('category_id', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.subcategory')),
                ('manufacturer_id', models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.manufacturer')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField(db_column='price', max_length=128)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.product')),
                ('retailer_id', models.ForeignKey(db_column='retailer_id', on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.retailer')),
            ],
            options={
                'db_table': 'prices',
                'ordering': ['id'],
            },
        ),
    ]
