# Generated by Django 4.1.7 on 2023-03-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.SmallIntegerField(db_column='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_number',
            field=models.BigIntegerField(db_column='catalog_number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(db_column='quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure_price',
            field=models.IntegerField(db_column='unit_of_measure_price'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='last_scan',
            field=models.BigIntegerField(db_column='last_scan'),
        ),
    ]
