# Generated by Django 4.1.7 on 2023-03-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0003_cart_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='type', max_length=256)),
                ('percent', models.SmallIntegerField(blank=True, db_column='percent', max_length=128, null=True)),
                ('fixed', models.SmallIntegerField(blank=True, db_column='fixed', max_length=128, null=True)),
                ('x', models.SmallIntegerField(blank=True, db_column='x', max_length=128, null=True)),
                ('y', models.SmallIntegerField(blank=True, db_column='y', max_length=128, null=True)),
                ('retailer_id', models.ForeignKey(db_column='retailer_id', on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.retailer')),
            ],
            options={
                'db_table': 'promos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.product')),
                ('promo_id', models.ForeignKey(db_column='promo_id', on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.promo')),
            ],
            options={
                'db_table': 'promos_products',
                'ordering': ['id'],
            },
        ),
    ]
