# Generated by Django 4.1.7 on 2023-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0004_promo_promoproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.BooleanField(db_column='cart_status', default=True),
        ),
    ]
