# Generated by Django 4.1.7 on 2023-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0005_alter_cart_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog_number',
            field=models.BigIntegerField(db_column='catalog_number', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(db_column='units', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product_id', 'retailer_id')},
        ),
    ]
