# Generated by Django 4.1.7 on 2023-04-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0006_alter_product_catalog_number_alter_product_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_fiber', models.CharField(blank=True, db_column='dietary_fiber', max_length=128, null=True)),
                ('sugars_from_carbohydrates', models.CharField(blank=True, db_column='sugars_from_carbohydrates', max_length=128, null=True)),
                ('energy', models.CharField(blank=True, db_column='energy', max_length=128, null=True)),
                ('proteins', models.CharField(blank=True, db_column='proteins', max_length=128, null=True)),
                ('carbohydrates', models.CharField(blank=True, db_column='carbohydrates', max_length=128, null=True)),
                ('fats', models.CharField(blank=True, db_column='fats', max_length=128, null=True)),
                ('sodium', models.CharField(blank=True, db_column='sodium', max_length=128, null=True)),
                ('salt', models.CharField(blank=True, db_column='salt', max_length=128, null=True)),
                ('cholesterol', models.CharField(blank=True, db_column='cholesterol', max_length=128, null=True)),
                ('saturated_fat', models.CharField(blank=True, db_column='saturated_fat', max_length=128, null=True)),
                ('trans_fatty_acids', models.CharField(blank=True, db_column='trans_fatty_acids', max_length=128, null=True)),
                ('sugar', models.CharField(blank=True, db_column='sugar', max_length=128, null=True)),
                ('iron', models.CharField(blank=True, db_column='iron', max_length=128, null=True)),
                ('calcium', models.CharField(blank=True, db_column='calcium', max_length=128, null=True)),
                ('local_rabbinate', models.CharField(blank=True, db_column='local_rabbinate', max_length=128, null=True)),
                ('kosher_type', models.CharField(blank=True, db_column='kosher_type', max_length=128, null=True)),
                ('kosher', models.CharField(blank=True, db_column='kosher', max_length=128, null=True)),
                ('passover', models.CharField(blank=True, db_column='passover', max_length=128, null=True)),
                ('component', models.TextField(db_column='component')),
                ('allergies_properties', models.CharField(blank=True, db_column='allergies_properties', max_length=128, null=True)),
                ('allergies_traces', models.CharField(blank=True, db_column='allergies_traces', max_length=128, null=True)),
            ],
            options={
                'db_table': 'products_info',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, db_column='image', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info_id',
            field=models.ForeignKey(blank=True, db_column='product_info_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineStoreApp.productinfo'),
        ),
    ]
