# Generated by Django 4.1.7 on 2023-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0007_productinfo_product_image_product_product_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(db_column='rating', default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_qty',
            field=models.IntegerField(db_column='sold_qty', default=0),
        ),
    ]
