# Generated by Django 4.1.7 on 2023-04-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0008_product_rating_product_sold_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('sub_category_id', models.ForeignKey(blank=True, db_column='sub_category_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.subcategory')),
            ],
            options={
                'db_table': 'sub_sub_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubSubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('sub_sub_category_id', models.ForeignKey(blank=True, db_column='sub_sub_category_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.subsubcategory')),
            ],
            options={
                'db_table': 'sub_sub_sub_categories',
                'ordering': ['id'],
            },
        ),
    ]
