# Generated by Django 4.1.7 on 2023-04-20 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0012_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='onlineStoreApp.subsubsubcategory'),
        ),
    ]
