# Generated by Django 4.1.7 on 2023-04-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0015_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='name', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubsubcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256, unique=True),
        ),
    ]
