# Generated by Django 4.1.7 on 2023-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0016_alter_category_name_alter_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checked',
            field=models.IntegerField(db_column='checked', default=0),
        ),
    ]
