# Generated by Django 4.1.7 on 2023-04-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0017_product_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='allergies_traces',
            field=models.CharField(blank=True, db_column='allergies_traces', max_length=512, null=True),
        ),
    ]
