# Generated by Django 4.1.7 on 2023-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0018_alter_productinfo_allergies_traces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256),
        ),
    ]
