# Generated by Django 4.1.7 on 2023-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0019_alter_subcategory_name_alter_subsubcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubsubcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256),
        ),
    ]
