# Generated by Django 4.1.7 on 2023-04-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0021_alter_productinfo_allergies_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='allergies_properties',
            field=models.CharField(blank=True, db_column='allergies_properties', max_length=512, null=True),
        ),
    ]
