# Generated by Django 4.1.7 on 2023-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0022_alter_productinfo_allergies_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='allergies_properties',
            field=models.CharField(blank=True, db_column='allergies_properties', max_length=768, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='allergies_traces',
            field=models.CharField(blank=True, db_column='allergies_traces', max_length=768, null=True),
        ),
    ]
