# Generated by Django 4.1.7 on 2023-04-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0024_product_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='retailer_id',
        ),
    ]
