# Generated by Django 4.1.7 on 2023-04-28 11:23

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0028_auto_20230428_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_key',
            field=models.UUIDField(db_column='cart_key', default=uuid.uuid4, unique=True),
        )
    ]
