# Generated by Django 4.1.7 on 2023-04-28 11:45

from django.db import migrations, models
import onlineStoreApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0029_auto_20230428_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.BigIntegerField(db_column='date', default=onlineStoreApp.models.current_timestamp),
        ),
    ]
