# Generated by Django 4.1.7 on 2023-04-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0030_alter_cart_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('cart_id', 'product_id')},
        ),
    ]
