# Generated by Django 4.1.7 on 2023-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0033_alter_product_unit_of_measure_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='cellulose',
            field=models.CharField(blank=True, db_column='cellulose', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='foreign_milk',
            field=models.CharField(blank=True, db_column='foreign_milk', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='humidity',
            field=models.CharField(blank=True, db_column='humidity', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='manufacturing_country',
            field=models.CharField(blank=True, db_column='manufacturing_country', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='phosphorus',
            field=models.CharField(blank=True, db_column='phosphorus', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_symbols',
            field=models.CharField(blank=True, db_column='product_symbols', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='taurine',
            field=models.CharField(blank=True, db_column='taurine', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubsubcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256, unique=True),
        ),
    ]
