# Generated by Django 4.1.7 on 2023-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0034_productinfo_cellulose_productinfo_foreign_milk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256),
        ),
        migrations.AlterField(
            model_name='subsubsubcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subsubcategory',
            unique_together={('name', 'sub_category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subsubsubcategory',
            unique_together={('name', 'sub_sub_category_id')},
        ),
    ]
