# Generated by Django 4.1.7 on 2023-06-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0035_alter_subcategory_name_alter_subsubcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='unit_of_measure',
            field=models.CharField(blank=True, db_column='unit_of_measure', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='unit_of_measure_price',
            field=models.DecimalField(blank=True, db_column='unit_of_measure_price', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='units',
            field=models.CharField(blank=True, db_column='units', max_length=128, null=True),
        ),
    ]
