# Generated by Django 4.1.7 on 2024-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0036_price_unit_of_measure_price_unit_of_measure_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='x',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='y',
        ),
        migrations.AddField(
            model_name='promo',
            name='additional_gift_count',
            field=models.IntegerField(blank=True, db_column='additional_gift_count', default=0, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='allow_multiple_discounts',
            field=models.BooleanField(db_column='allow_multiple_discounts', default=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='club_id',
            field=models.IntegerField(blank=True, db_column='club_id', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='discount_rate',
            field=models.DecimalField(blank=True, db_column='discount_rate', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='discount_type',
            field=models.IntegerField(blank=True, db_column='discount_type', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='discounted_price',
            field=models.DecimalField(blank=True, db_column='discounted_price', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='end_date',
            field=models.DateField(blank=True, db_column='end_date', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='end_hour',
            field=models.TimeField(blank=True, db_column='end_hour', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='is_weighted_promo',
            field=models.BooleanField(db_column='is_weighted_promo', default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='max_qty',
            field=models.DecimalField(blank=True, db_column='max_qty', decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='min_no_of_item_offered',
            field=models.IntegerField(blank=True, db_column='min_no_of_item_offered', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='min_qty',
            field=models.DecimalField(blank=True, db_column='min_qty', decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='promotion_id',
            field=models.IntegerField(blank=True, db_column='promotion_id', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='remark',
            field=models.CharField(blank=True, db_column='remark', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='reward_type',
            field=models.IntegerField(blank=True, db_column='reward_type', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='start_date',
            field=models.DateField(blank=True, db_column='start_date', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='start_hour',
            field=models.TimeField(blank=True, db_column='start_hour', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='update_date',
            field=models.DateTimeField(blank=True, db_column='update_date', null=True),
        ),
        migrations.AddField(
            model_name='promoproduct',
            name='is_gift_item',
            field=models.BooleanField(db_column='is_gift_item', default=False),
        ),
    ]
