# Generated by Django 4.1.7 on 2025-03-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStoreApp', '0037_remove_promo_fixed_remove_promo_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='allergies_properties',
            field=models.CharField(blank=True, db_column='allergies_properties', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='allergies_traces',
            field=models.CharField(blank=True, db_column='allergies_traces', max_length=1500, null=True),
        ),
    ]
